Take environment variables for database credentials
hotosm/galaxy-api pull request #85
Opened 2021-11-30 14:53 UTC by eternaltyro

2021-11-30 14:54 UTC, eternaltyro commented
@itskshitiz321 @JorgeMartinezG @omranlm please help validate my changes including syntax and functionality. TIA for the help.

2021-12-01 13:09 UTC, itskshitiz321 submitted a review, later dismissed
These config files are defined in API/__init__.py  needs to be inside src/config.py

2021-12-06 14:50 UTC, eternaltyro commented
@itskshitiz321 @JorgeMartinezG made the changes you suggested. Please review.  cc: @ramyaragupathy

2021-12-07 10:27 UTC, eternaltyro commented
Syntax errors fixed.

2021-12-14 17:02 UTC, itskshitiz321 requested changes

2021-12-15 01:40 UTC, eternaltyro commented on API/changesets/routers.py
> +    db_params = get_db_connection_params()
@itskshitiz321 done.

2021-12-15 01:40 UTC, eternaltyro commented on API/countries/routers.py
> +    db_params = get_db_connection_params()
@itskshitiz321 done.

2021-12-15 01:41 UTC, eternaltyro commented
Added missing imports.

2021-12-15 06:26 UTC, merged